### ISSUE TITLE
Can you share your recording setup for your egghead.io tutorials?

### ISSUE THREAD

**Issue by gr2m** [kentcdodds/ama#341]
I’ve watched your [The Beginner's Guide to ReactJS](https://egghead.io/courses/the-beginner-s-guide-to-reactjs) and it’s absolutely fabulous! I very much like your setup with your editor on the left and the browser on the right, in which you can pull up the dev tools as you need it. Can you share your setup of that? I think it’s a great setup for technical follow along workshops like this one

[![image](https://user-images.githubusercontent.com/39992/33799367-f33993c2-dcde-11e7-9af6-0de10e8a71e1.png)](https://egghead.io/courses/the-beginner-s-guide-to-reactjs)

**Comment by kentcdodds** [comment]
Hi @gr2m! I recorded a video to show you how I do it all! I hope it's helpful!

https://youtu.be/t2CZsbzbbNc

Here's a related question/answer: https://github.com/kentcdodds/ama/issues/107

And here's a thing I copy/pasted from the video:

```
npx browser-sync start --server --files "**/index.html" --no-open --no-notify --directory
```

Thanks for the question!

**Comment by v1adko** [comment]
@kentcdodds Great. The video just showed up in my youtube feed :)

 I decided to create a CRA repo to follow along your advanced patterns course (for hot reloading and more traditional setup), and I expect more people are gonna take it and also code along side, so I think it would be useful to provide a link to the video on both introductory videos on egghead in the description.

There were also times when the code changes from the end of the last video to the beginning of the next which made it a little harder to follow (had to look at the repo and figure out the new parts, and the repo had only the final versions of the lessons). I understand that the course was not meant for coding along, but I personally remember things better this way. So it would be cool if you mention some help [to setup a workflow] for the kind of learners like me. 
Just some feedback that I think can make your great courses even better.

**Comment by gr2m** [comment]
@kentcdodds can you share your custom atom editor styles for the egghead recordings?

**Comment by kentcdodds** [comment]
Sure! Here's my stylesheet:

```css
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed and saved.
 *
 * Add your own CSS or Less to fully customize Atom.
 * If you are unfamiliar with Less, you can read more about it here:
 * http://lesscss.org
 */

/*
 * Examples
 * (To see them, uncomment and save)
 */

// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

.gutter[gutter-name='linter-ui-default'] {
  display: none;
}

.atom-dock-content-wrapper.left ul.list-inline.tab-bar.inset-panel {
  display: none;
}

.atom-dock-toggle-button {
  display: none;
}

/* workshop/talk adjustments */
/*
.list-group .icon::before,
.list-tree .icon::before,
.list-tree.has-collapsable-children
  .list-nested-item.collapsed
  > .list-item::before,
.list-tree.has-collapsable-children .list-nested-item > .list-item::before,
.tree-view {
  font-size: 22px;
  min-width: 22px;
}
atom-text-editor {
  font-size: 24px;
}
atom-text-editor .gutter {
  min-width: 0em;
}
.tab-bar {
  zoom: 1.6;
}
.tab-bar .title {
  font-size: 15px;
}
status-bar-file {
  font-size: 2.7em;
}
atom-panel.modal {
  max-width: 90%;
  zoom: 1.6;
}
/**/

/* no header/footer bars */
/*
.tab-bar {
  display: none;
}
atom-panel-container.footer {
  display: none;
}
/**/

/* no wrap-guide */
/*
.wrap-guide {
  display: none !important;
}
/**/

/* no git changes */
/*
.line-number.git-line-modified,
.line-number.git-line-added {
  border-left-color: transparent !important;
}
.line-number.git-line-removed::before,
.line-number.git-line-removed::after {
  opacity: 0;
}
/**/

/* no line numbers */
/*
.gutter-container {
  opacity: 0;
}
.line-number {
  width: 10px;
}
/**/

/* code only */
/*
atom-panel-container.footer {
  display: none;
}
.gutter-container {
  opacity: 0;
}
atom-pane-container.panes ul.list-inline.tab-bar.inset-panel {
  opacity: 0;
}
atom-pane.pane {
  background-color: rgb(250, 250, 250);
}
/**/

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}

// To style other content in the text editor's shadow DOM, use the ::shadow expression
atom-text-editor::shadow .cursor {
  // border-color: red;
}

atom-text-editor .indent-guide {
  // there was a really annoying line on the left of things
  box-shadow: inherit;
}

/* egghead lesson adjustments */
/*
.list-group .icon::before,
.list-tree .icon::before,
.list-tree.has-collapsable-children
  .list-nested-item.collapsed
  > .list-item::before,
.list-tree.has-collapsable-children .list-nested-item > .list-item::before,
.tree-view {
  font-size: 22px;
  min-width: 22px;
}
atom-text-editor {
  font-size: 24px;
}
atom-text-editor .gutter {
  min-width: 0em;
}
.tab-bar {
  zoom: 1.6;
}
.tab-bar .title {
  font-size: 15px;
}
status-bar-file {
  font-size: 2.7em;
}
atom-panel.modal {
  max-width: 90%;
  zoom: 1.6;
}

// no header/footer bars
.tab-bar {
  display: none;
}
atom-panel-container.footer {
  display: none;
}

// no wrap-guide
.wrap-guide {
  display: none !important;
}

// no git changes
.line-number.git-line-modified,
.line-number.git-line-added {
  border-left-color: transparent !important;
}
.line-number.git-line-removed::before,
.line-number.git-line-removed::after {
  opacity: 0;
}

// no chevron things
atom-text-editor .gutter .line-number .icon-right {
  visibility: hidden !important;
}
/**/
```

Good luck!
